// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Q3cCaJzgLbctmZg9gjg8T3uRshu6V_g',
    appId: '1:393358394480:web:ed33ec32d6ac1dca3120b5',
    messagingSenderId: '393358394480',
    projectId: 'lawise-5a5a7',
    authDomain: 'lawise-5a5a7.firebaseapp.com',
    storageBucket: 'lawise-5a5a7.firebasestorage.app',
    measurementId: 'G-2W7BYG5CGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Q3cCaJzgLbctmZg9gjg8T3uRshu6V_g',
    appId: '1:393358394480:android:ed33ec32d6ac1dca3120b5',
    messagingSenderId: '393358394480',
    projectId: 'lawise-5a5a7',
    storageBucket: 'lawise-5a5a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Q3cCaJzgLbctmZg9gjg8T3uRshu6V_g',
    appId: '1:393358394480:ios:ed33ec32d6ac1dca3120b5',
    messagingSenderId: '393358394480',
    projectId: 'lawise-5a5a7',
    storageBucket: 'lawise-5a5a7.firebasestorage.app',
    iosBundleId: 'com.example.lawise',
  );
}
