
class LawDocument {
  final String id;
  final String title;
  final String description;
  final String category;
  final DateTime publishedDate;
  final String documentType;
  final String content;
  final List<String> tags;
  final bool isBookmarked;
  final String? fileUrl;
  final String? filePath;
  final int viewCount;
  final DateTime lastUpdated;

  LawDocument({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.publishedDate,
    required this.documentType,
    required this.content,
    required this.tags,
    required this.isBookmarked,
    this.fileUrl,
    this.filePath,
    required this.viewCount,
    required this.lastUpdated,
  });

  LawDocument copyWith({
    String? id,
    String? title,
    String? description,
    String? category,
    DateTime? publishedDate,
    String? documentType,
    String? content,
    List<String>? tags,
    bool? isBookmarked,
    String? fileUrl,
    String? filePath,
    int? viewCount,
    DateTime? lastUpdated,
  }) {
    return LawDocument(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      category: category ?? this.category,
      publishedDate: publishedDate ?? this.publishedDate,
      documentType: documentType ?? this.documentType,
      content: content ?? this.content,
      tags: tags ?? this.tags,
      isBookmarked: isBookmarked ?? this.isBookmarked,
      fileUrl: fileUrl ?? this.fileUrl,
      filePath: filePath ?? this.filePath,
      viewCount: viewCount ?? this.viewCount,
      lastUpdated: lastUpdated ?? this.lastUpdated,
    );
  }
}

class LawCategory {
  final String id;
  final String name;
  final String description;
  final String iconName;
  final int documentCount;
  final String colorHex;

  LawCategory({
    required this.id,
    required this.name,
    required this.description,
    required this.iconName,
    required this.documentCount,
    required this.colorHex,
  });
}

class SearchResult {
  final List<LawDocument> documents;
  final List<LawCategory> categories;
  final int totalResults;
  final String query;

  SearchResult({
    required this.documents,
    required this.categories,
    required this.totalResults,
    required this.query,
  });
}

// Mock data for development - Pakistan Laws
class MockLawLibraryData {
  static final List<LawDocument> mockDocuments = [
    // Constitutional Law (10+ documents)
    LawDocument(
      id: '1',
      title: 'Constitution of Pakistan 1973',
      description: 'The supreme law of Pakistan establishing the framework of government, fundamental rights, and directive principles',
      category: 'Constitutional Law',
      publishedDate: DateTime(1973, 4, 14),
      documentType: 'Constitution',
      content: 'The Constitution of Pakistan 1973 is the supreme law of Pakistan. It establishes the framework of government, outlines fundamental rights of citizens, and provides directive principles of state policy...',
      tags: ['constitution', 'fundamental rights', 'government', 'supreme law'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 15420,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'const_2',
      title: 'Legal Framework Order 2002',
      description: 'Constitutional amendments and legal framework established by General Musharraf',
      category: 'Constitutional Law',
      publishedDate: DateTime(2002, 8, 21),
      documentType: 'Order',
      content: 'The Legal Framework Order 2002 introduced significant constitutional amendments and established the legal framework for governance...',
      tags: ['constitutional amendment', 'legal framework', 'governance'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3420,
      lastUpdated: DateTime.now().subtract(const Duration(days: 5)),
    ),
    LawDocument(
      id: 'const_3',
      title: 'Eighteenth Amendment Act 2010',
      description: 'Major constitutional amendment transferring powers from President to Parliament',
      category: 'Constitutional Law',
      publishedDate: DateTime(2010, 4, 19),
      documentType: 'Amendment',
      content: 'The Eighteenth Amendment significantly altered the balance of power in Pakistan by transferring executive powers from the President to the Prime Minister...',
      tags: ['constitutional amendment', 'parliamentary system', 'devolution'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 8750,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'const_4',
      title: 'Nineteenth Amendment Act 2010',
      description: 'Constitutional amendment regarding appointment of judges',
      category: 'Constitutional Law',
      publishedDate: DateTime(2010, 12, 31),
      documentType: 'Amendment',
      content: 'The Nineteenth Amendment established the Judicial Commission for appointment of judges and reformed the judicial appointment process...',
      tags: ['judicial appointment', 'judicial commission', 'constitutional reform'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4320,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'const_5',
      title: 'Twenty-Fifth Amendment Act 2018',
      description: 'Constitutional amendment regarding FATA merger with KPK',
      category: 'Constitutional Law',
      publishedDate: DateTime(2018, 5, 31),
      documentType: 'Amendment',
      content: 'The Twenty-Fifth Amendment merged the Federally Administered Tribal Areas (FATA) with Khyber Pakhtunkhwa province...',
      tags: ['FATA merger', 'provincial integration', 'tribal areas'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'const_6',
      title: 'National Accountability Ordinance 1999',
      description: 'Anti-corruption law establishing National Accountability Bureau',
      category: 'Constitutional Law',
      publishedDate: DateTime(1999, 11, 16),
      documentType: 'Ordinance',
      content: 'The National Accountability Ordinance established NAB to combat corruption and recover looted national wealth...',
      tags: ['anti-corruption', 'accountability', 'NAB'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 7650,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'const_7',
      title: 'Elections Act 2017',
      description: 'Comprehensive law governing electoral processes in Pakistan',
      category: 'Constitutional Law',
      publishedDate: DateTime(2017, 10, 2),
      documentType: 'Act',
      content: 'The Elections Act 2017 provides comprehensive framework for conducting elections, voter registration, and electoral disputes...',
      tags: ['elections', 'electoral process', 'voting rights'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 9340,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    LawDocument(
      id: 'const_8',
      title: 'Political Parties Order 2002',
      description: 'Law regulating formation and functioning of political parties',
      category: 'Constitutional Law',
      publishedDate: DateTime(2002, 6, 15),
      documentType: 'Order',
      content: 'The Political Parties Order regulates the formation, registration, and functioning of political parties in Pakistan...',
      tags: ['political parties', 'party registration', 'democratic process'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5230,
      lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
    ),
    LawDocument(
      id: 'const_9',
      title: 'Freedom of Information Ordinance 2002',
      description: 'Law ensuring public access to government information',
      category: 'Constitutional Law',
      publishedDate: DateTime(2002, 10, 21),
      documentType: 'Ordinance',
      content: 'The Freedom of Information Ordinance guarantees citizens right to access information held by public bodies...',
      tags: ['freedom of information', 'transparency', 'public access'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4780,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    LawDocument(
      id: 'const_10',
      title: 'National Commission for Human Rights Act 2012',
      description: 'Law establishing national human rights commission',
      category: 'Constitutional Law',
      publishedDate: DateTime(2012, 5, 30),
      documentType: 'Act',
      content: 'The Act establishes the National Commission for Human Rights to protect and promote human rights in Pakistan...',
      tags: ['human rights', 'commission', 'protection'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3890,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    
    // Criminal Law (10+ documents)
    LawDocument(
      id: '2',
      title: 'Pakistan Penal Code 1860',
      description: 'The main criminal code of Pakistan defining offenses and their punishments',
      category: 'Criminal Law',
      publishedDate: DateTime(1860, 10, 6),
      documentType: 'Code',
      content: 'The Pakistan Penal Code (PPC) is the main criminal code of Pakistan. It defines various offenses and prescribes punishments for them. The code covers crimes against the state, public tranquility, human body, property, and more...',
      tags: ['criminal law', 'penal code', 'offenses', 'punishments'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 12850,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: '3',
      title: 'Code of Criminal Procedure 1898',
      description: 'Procedural law governing criminal proceedings in Pakistan',
      category: 'Criminal Law',
      publishedDate: DateTime(1898, 3, 25),
      documentType: 'Code',
      content: 'The Code of Criminal Procedure (CrPC) governs the procedural aspects of criminal law in Pakistan. It outlines the process of investigation, trial, and appeal in criminal cases...',
      tags: ['criminal procedure', 'investigation', 'trial', 'appeal'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 9870,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    LawDocument(
      id: 'crim_3',
      title: 'Anti-Terrorism Act 1997',
      description: 'Comprehensive law to combat terrorism and terrorist activities',
      category: 'Criminal Law',
      publishedDate: DateTime(1997, 8, 20),
      documentType: 'Act',
      content: 'The Anti-Terrorism Act 1997 provides legal framework to combat terrorism, defines terrorist acts, and establishes special courts for trial of terrorism cases...',
      tags: ['terrorism', 'anti-terrorism', 'special courts', 'security'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 11200,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'crim_4',
      title: 'Prevention of Electronic Crimes Act 2016',
      description: 'Law addressing cybercrimes and electronic offenses',
      category: 'Criminal Law',
      publishedDate: DateTime(2016, 8, 11),
      documentType: 'Act',
      content: 'PECA 2016 addresses cybercrimes including unauthorized access, data damage, electronic fraud, and cyber terrorism...',
      tags: ['cybercrime', 'electronic crimes', 'data protection', 'cyber security'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 8940,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'crim_5',
      title: 'Control of Narcotic Substances Act 1997',
      description: 'Law regulating narcotic drugs and psychotropic substances',
      category: 'Criminal Law',
      publishedDate: DateTime(1997, 9, 25),
      documentType: 'Act',
      content: 'The CNSA 1997 regulates narcotic drugs, psychotropic substances, and precursor chemicals to prevent drug trafficking and abuse...',
      tags: ['narcotics', 'drug control', 'trafficking', 'substance abuse'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6780,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'crim_6',
      title: 'Arms Ordinance 1965',
      description: 'Law regulating possession and use of arms and ammunition',
      category: 'Criminal Law',
      publishedDate: DateTime(1965, 4, 20),
      documentType: 'Ordinance',
      content: 'The Arms Ordinance regulates the manufacture, sale, possession, and use of arms and ammunition in Pakistan...',
      tags: ['arms control', 'weapons', 'ammunition', 'licensing'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5430,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'crim_7',
      title: 'Qanun-e-Shahadat Order 1984',
      description: 'Law of evidence governing admissibility of evidence in courts',
      category: 'Criminal Law',
      publishedDate: DateTime(1984, 10, 1),
      documentType: 'Order',
      content: 'The Qanun-e-Shahadat Order governs the law of evidence in Pakistan, including rules for admissibility and evaluation of evidence...',
      tags: ['evidence law', 'testimony', 'admissibility', 'court proceedings'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 7650,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    LawDocument(
      id: 'crim_8',
      title: 'Juvenile Justice System Act 2018',
      description: 'Law governing treatment of juvenile offenders',
      category: 'Criminal Law',
      publishedDate: DateTime(2018, 7, 1),
      documentType: 'Act',
      content: 'The JJSA 2018 establishes a separate justice system for juvenile offenders focusing on rehabilitation rather than punishment...',
      tags: ['juvenile justice', 'child offenders', 'rehabilitation', 'youth courts'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4320,
      lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
    ),
    LawDocument(
      id: 'crim_9',
      title: 'Criminal Law Amendment Act 2004',
      description: 'Amendments to criminal law including honor killing provisions',
      category: 'Criminal Law',
      publishedDate: DateTime(2004, 12, 1),
      documentType: 'Amendment',
      content: 'The Criminal Law Amendment Act 2004 introduced provisions against honor killing and strengthened laws against violence against women...',
      tags: ['honor killing', 'women protection', 'criminal amendment', 'violence'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 15)),
    ),
    LawDocument(
      id: 'crim_10',
      title: 'Anti-Money Laundering Act 2010',
      description: 'Law to prevent money laundering and terrorist financing',
      category: 'Criminal Law',
      publishedDate: DateTime(2010, 3, 6),
      documentType: 'Act',
      content: 'The AMLA 2010 criminalizes money laundering and provides framework for prevention of money laundering and terrorist financing...',
      tags: ['money laundering', 'financial crimes', 'terrorist financing', 'compliance'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5670,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    
    // Civil Law (10+ documents)
    LawDocument(
      id: '4',
      title: 'Civil Procedure Code 1908',
      description: 'Procedural law governing civil litigation in Pakistan',
      category: 'Civil Law',
      publishedDate: DateTime(1908, 1, 1),
      documentType: 'Code',
      content: 'The Civil Procedure Code (CPC) governs the procedure for civil litigation in Pakistan. It provides the framework for filing suits, conducting trials, and executing decrees...',
      tags: ['civil procedure', 'litigation', 'suits', 'decrees'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 8950,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: '5',
      title: 'Contract Act 1872',
      description: 'Law governing contracts and agreements in Pakistan',
      category: 'Civil Law',
      publishedDate: DateTime(1872, 4, 25),
      documentType: 'Act',
      content: 'The Contract Act 1872 governs the law of contracts in Pakistan. It defines what constitutes a valid contract, the rights and obligations of parties, and remedies for breach of contract...',
      tags: ['contracts', 'agreements', 'breach', 'remedies'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 7650,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'civil_3',
      title: 'Sale of Goods Act 1930',
      description: 'Law governing sale and purchase of goods',
      category: 'Civil Law',
      publishedDate: DateTime(1930, 7, 1),
      documentType: 'Act',
      content: 'The Sale of Goods Act 1930 governs contracts for sale of goods, including conditions, warranties, and transfer of ownership...',
      tags: ['sale of goods', 'commercial law', 'warranties', 'ownership transfer'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6420,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'civil_4',
      title: 'Partnership Act 1932',
      description: 'Law governing business partnerships in Pakistan',
      category: 'Civil Law',
      publishedDate: DateTime(1932, 4, 1),
      documentType: 'Act',
      content: 'The Partnership Act 1932 defines partnership relationships, rights and duties of partners, and dissolution of partnerships...',
      tags: ['partnership', 'business law', 'partners rights', 'dissolution'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    LawDocument(
      id: 'civil_5',
      title: 'Limitation Act 1908',
      description: 'Law prescribing time limits for filing legal proceedings',
      category: 'Civil Law',
      publishedDate: DateTime(1908, 9, 1),
      documentType: 'Act',
      content: 'The Limitation Act 1908 prescribes the time limits within which legal proceedings must be instituted in courts...',
      tags: ['limitation period', 'time limits', 'legal proceedings', 'statute of limitations'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 7230,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'civil_6',
      title: 'Specific Relief Act 1877',
      description: 'Law providing specific remedies in civil matters',
      category: 'Civil Law',
      publishedDate: DateTime(1877, 3, 1),
      documentType: 'Act',
      content: 'The Specific Relief Act 1877 provides for specific performance of contracts, injunctions, and other equitable remedies...',
      tags: ['specific relief', 'injunctions', 'specific performance', 'equitable remedies'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4670,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    LawDocument(
      id: 'civil_7',
      title: 'Negotiable Instruments Act 1881',
      description: 'Law governing promissory notes, bills of exchange, and cheques',
      category: 'Civil Law',
      publishedDate: DateTime(1881, 12, 9),
      documentType: 'Act',
      content: 'The Negotiable Instruments Act 1881 governs promissory notes, bills of exchange, and cheques including their negotiation and dishonor...',
      tags: ['negotiable instruments', 'promissory notes', 'bills of exchange', 'cheques'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5340,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'civil_8',
      title: 'Arbitration Act 1940',
      description: 'Law governing arbitration proceedings and awards',
      category: 'Civil Law',
      publishedDate: DateTime(1940, 4, 1),
      documentType: 'Act',
      content: 'The Arbitration Act 1940 provides framework for arbitration proceedings, appointment of arbitrators, and enforcement of awards...',
      tags: ['arbitration', 'alternative dispute resolution', 'arbitrators', 'awards'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'civil_9',
      title: 'Consumer Protection Act 2005',
      description: 'Law protecting consumer rights and interests',
      category: 'Civil Law',
      publishedDate: DateTime(2005, 7, 1),
      documentType: 'Act',
      content: 'The Consumer Protection Act 2005 protects consumer rights, establishes consumer courts, and provides remedies for consumer grievances...',
      tags: ['consumer protection', 'consumer rights', 'consumer courts', 'grievances'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6780,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'civil_10',
      title: 'Legal Practitioners and Bar Councils Act 1973',
      description: 'Law regulating legal profession and bar councils',
      category: 'Civil Law',
      publishedDate: DateTime(1973, 5, 10),
      documentType: 'Act',
      content: 'The Act regulates the legal profession, establishes bar councils, and prescribes standards for legal practitioners...',
      tags: ['legal profession', 'bar councils', 'advocates', 'professional standards'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4520,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 9)),
    ),
    
    // Family Law (10+ documents)
    LawDocument(
      id: '6',
      title: 'Muslim Family Laws Ordinance 1961',
      description: 'Laws governing marriage, divorce, and family matters for Muslims in Pakistan',
      category: 'Family Law',
      publishedDate: DateTime(1961, 3, 2),
      documentType: 'Ordinance',
      content: 'The Muslim Family Laws Ordinance 1961 governs marriage, divorce, maintenance, and succession matters for Muslims in Pakistan. It provides procedures for registration of marriages and divorces...',
      tags: ['family law', 'marriage', 'divorce', 'muslim law'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6780,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: '7',
      title: 'Guardian and Wards Act 1890',
      description: 'Law governing guardianship and custody of minors',
      category: 'Family Law',
      publishedDate: DateTime(1890, 7, 1),
      documentType: 'Act',
      content: 'The Guardian and Wards Act 1890 governs the appointment of guardians for minors and the custody of children. It outlines the powers and duties of guardians and the welfare of wards...',
      tags: ['guardianship', 'custody', 'minors', 'welfare'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5420,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    LawDocument(
      id: 'family_3',
      title: 'West Pakistan Family Courts Act 1964',
      description: 'Law establishing family courts for matrimonial disputes',
      category: 'Family Law',
      publishedDate: DateTime(1964, 7, 1),
      documentType: 'Act',
      content: 'The West Pakistan Family Courts Act establishes family courts with exclusive jurisdiction over matrimonial disputes and family matters...',
      tags: ['family courts', 'matrimonial disputes', 'jurisdiction', 'family matters'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4320,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'family_4',
      title: 'Child Marriage Restraint Act 1929',
      description: 'Law prohibiting child marriages in Pakistan',
      category: 'Family Law',
      publishedDate: DateTime(1929, 9, 28),
      documentType: 'Act',
      content: 'The Child Marriage Restraint Act prohibits marriage of children below specified ages and prescribes punishments for violations...',
      tags: ['child marriage', 'minimum age', 'child protection', 'marriage laws'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5670,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    LawDocument(
      id: 'family_5',
      title: 'Dissolution of Muslim Marriages Act 1939',
      description: 'Law governing dissolution of Muslim marriages',
      category: 'Family Law',
      publishedDate: DateTime(1939, 4, 17),
      documentType: 'Act',
      content: 'The Act provides grounds for dissolution of Muslim marriages by women and procedures for obtaining divorce...',
      tags: ['muslim divorce', 'dissolution', 'womens rights', 'marriage dissolution'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3890,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'family_6',
      title: 'Muslim Personal Law (Shariat) Application Act 1937',
      description: 'Law applying Islamic personal law to Muslims',
      category: 'Family Law',
      publishedDate: DateTime(1937, 10, 7),
      documentType: 'Act',
      content: 'The Act applies Islamic personal law (Shariat) to Muslims in matters of marriage, divorce, inheritance, and family relations...',
      tags: ['shariat law', 'islamic law', 'personal law', 'inheritance'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6240,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 15)),
    ),
    LawDocument(
      id: 'family_7',
      title: 'Dowry and Bridal Gifts (Restriction) Act 1976',
      description: 'Law restricting dowry and bridal gifts',
      category: 'Family Law',
      publishedDate: DateTime(1976, 2, 15),
      documentType: 'Act',
      content: 'The Act restricts the giving and taking of dowry and bridal gifts beyond prescribed limits to prevent exploitation...',
      tags: ['dowry restriction', 'bridal gifts', 'marriage expenses', 'social reform'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 2890,
      lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
    ),
    LawDocument(
      id: 'family_8',
      title: 'Protection of Women (Criminal Laws Amendment) Act 2006',
      description: 'Law protecting women from violence and discrimination',
      category: 'Family Law',
      publishedDate: DateTime(2006, 12, 1),
      documentType: 'Act',
      content: 'The Act provides protection to women from violence, harassment, and discrimination in family and social contexts...',
      tags: ['women protection', 'domestic violence', 'harassment', 'gender rights'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 7450,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    LawDocument(
      id: 'family_9',
      title: 'Maintenance of Parents Act 2013',
      description: 'Law ensuring maintenance and care of elderly parents',
      category: 'Family Law',
      publishedDate: DateTime(2013, 5, 20),
      documentType: 'Act',
      content: 'The Act makes it mandatory for children to provide maintenance and care to their elderly parents and establishes enforcement mechanisms...',
      tags: ['elderly care', 'parent maintenance', 'family obligations', 'senior citizens'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4560,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'family_10',
      title: 'Succession Act 1925',
      description: 'Law governing inheritance and succession for non-Muslims',
      category: 'Family Law',
      publishedDate: DateTime(1925, 1, 1),
      documentType: 'Act',
      content: 'The Succession Act governs inheritance, wills, and succession matters for non-Muslims in Pakistan...',
      tags: ['succession', 'inheritance', 'wills', 'non-muslim law'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5230,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    
    // Corporate Law (10+ documents)
    LawDocument(
      id: '8',
      title: 'Companies Act 2017',
      description: 'Comprehensive law governing incorporation and regulation of companies in Pakistan',
      category: 'Corporate Law',
      publishedDate: DateTime(2017, 5, 30),
      documentType: 'Act',
      content: 'The Companies Act 2017 is the primary legislation governing the incorporation, regulation, and winding up of companies in Pakistan. It replaced the Companies Ordinance 1984...',
      tags: ['companies', 'incorporation', 'corporate governance', 'business'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 11200,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    LawDocument(
      id: '9',
      title: 'Securities Act 2015',
      description: 'Law regulating securities markets and capital market operations',
      category: 'Corporate Law',
      publishedDate: DateTime(2015, 4, 15),
      documentType: 'Act',
      content: 'The Securities Act 2015 regulates the securities markets in Pakistan. It provides for the establishment and regulation of stock exchanges, protection of investors, and prevention of fraudulent practices...',
      tags: ['securities', 'stock exchange', 'investors', 'capital market'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4850,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'corp_3',
      title: 'Competition Act 2010',
      description: 'Law promoting competition and preventing monopolistic practices',
      category: 'Corporate Law',
      publishedDate: DateTime(2010, 10, 13),
      documentType: 'Act',
      content: 'The Competition Act 2010 promotes competition, prevents monopolistic practices, and protects consumer interests in the market...',
      tags: ['competition law', 'antitrust', 'monopoly', 'market regulation'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6340,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'corp_4',
      title: 'Corporate Restructuring Companies Act 2016',
      description: 'Law facilitating corporate restructuring and rehabilitation',
      category: 'Corporate Law',
      publishedDate: DateTime(2016, 5, 30),
      documentType: 'Act',
      content: 'The Act provides framework for corporate restructuring, rehabilitation of sick companies, and protection of stakeholder interests...',
      tags: ['corporate restructuring', 'rehabilitation', 'insolvency', 'stakeholder protection'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    LawDocument(
      id: 'corp_5',
      title: 'Foreign Exchange Regulation Act 1947',
      description: 'Law regulating foreign exchange transactions',
      category: 'Corporate Law',
      publishedDate: DateTime(1947, 3, 7),
      documentType: 'Act',
      content: 'FERA regulates foreign exchange transactions, foreign investments, and cross-border financial activities...',
      tags: ['foreign exchange', 'forex regulation', 'foreign investment', 'currency control'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5670,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'corp_6',
      title: 'Intellectual Property Organization Act 2012',
      description: 'Law establishing intellectual property protection framework',
      category: 'Corporate Law',
      publishedDate: DateTime(2012, 4, 15),
      documentType: 'Act',
      content: 'The Act establishes the Intellectual Property Organization and provides framework for protection of patents, trademarks, and copyrights...',
      tags: ['intellectual property', 'patents', 'trademarks', 'copyrights'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4520,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    LawDocument(
      id: 'corp_7',
      title: 'Public Procurement Regulatory Authority Act 2009',
      description: 'Law regulating public procurement processes',
      category: 'Corporate Law',
      publishedDate: DateTime(2009, 2, 1),
      documentType: 'Act',
      content: 'PPRA Act regulates public procurement, ensures transparency, and promotes fair competition in government contracts...',
      tags: ['public procurement', 'government contracts', 'transparency', 'bidding'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3240,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'corp_8',
      title: 'Monopolies and Restrictive Trade Practices Ordinance 1970',
      description: 'Law preventing monopolistic and restrictive trade practices',
      category: 'Corporate Law',
      publishedDate: DateTime(1970, 12, 25),
      documentType: 'Ordinance',
      content: 'MRTPO prevents monopolistic practices, restrictive trade practices, and promotes fair competition in business...',
      tags: ['monopoly control', 'trade practices', 'fair competition', 'business regulation'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 2890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'corp_9',
      title: 'Small and Medium Enterprises Development Act 2013',
      description: 'Law promoting development of small and medium enterprises',
      category: 'Corporate Law',
      publishedDate: DateTime(2013, 8, 20),
      documentType: 'Act',
      content: 'SMEDA Act promotes development of SMEs, provides support mechanisms, and facilitates access to finance and markets...',
      tags: ['SME development', 'small business', 'entrepreneurship', 'business support'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4670,
      lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
    ),
    LawDocument(
      id: 'corp_10',
      title: 'Export Promotion Act 1958',
      description: 'Law promoting exports and international trade',
      category: 'Corporate Law',
      publishedDate: DateTime(1958, 6, 15),
      documentType: 'Act',
      content: 'The Export Promotion Act facilitates exports, provides incentives to exporters, and promotes international trade...',
      tags: ['export promotion', 'international trade', 'export incentives', 'trade facilitation'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3450,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 9)),
    ),
    
    // Labor Law
    LawDocument(
      id: '10',
      title: 'Industrial Relations Act 2012',
      description: 'Law governing industrial relations, trade unions, and labor disputes',
      category: 'Labor Law',
      publishedDate: DateTime(2012, 10, 15),
      documentType: 'Act',
      content: 'The Industrial Relations Act 2012 governs the relationship between employers and employees, formation of trade unions, collective bargaining, and resolution of industrial disputes...',
      tags: ['industrial relations', 'trade unions', 'collective bargaining', 'labor disputes'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6340,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    
    LawDocument(
      id: '11',
      title: 'Factories Act 1934',
      description: 'Law regulating working conditions and safety in factories',
      category: 'Labor Law',
      publishedDate: DateTime(1934, 9, 1),
      documentType: 'Act',
      content: 'The Factories Act 1934 regulates the working conditions in factories, including provisions for health, safety, welfare of workers, working hours, and employment of women and children...',
      tags: ['factories', 'working conditions', 'safety', 'workers welfare'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3920,
      lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
    ),
    LawDocument(
      id: 'labor_3',
      title: 'Minimum Wages Ordinance 1961',
      description: 'Law establishing minimum wage standards for workers',
      category: 'Labor Law',
      publishedDate: DateTime(1961, 3, 3),
      documentType: 'Ordinance',
      content: 'The Minimum Wages Ordinance 1961 establishes minimum wage standards for different categories of workers and provides for periodic revision of wages...',
      tags: ['minimum wages', 'wage standards', 'worker compensation', 'labor rights'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5450,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 15)),
    ),
    LawDocument(
      id: 'labor_4',
      title: 'Employment of Children Act 1991',
      description: 'Law prohibiting employment of children in hazardous occupations',
      category: 'Labor Law',
      publishedDate: DateTime(1991, 4, 8),
      documentType: 'Act',
      content: 'The Act prohibits employment of children below 14 years in hazardous occupations and regulates working conditions for child workers...',
      tags: ['child labor', 'child protection', 'hazardous work', 'minor employment'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4320,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'labor_5',
      title: 'Workers Welfare Fund Ordinance 1971',
      description: 'Law establishing workers welfare fund for industrial workers',
      category: 'Labor Law',
      publishedDate: DateTime(1971, 11, 15),
      documentType: 'Ordinance',
      content: 'The Ordinance establishes Workers Welfare Fund for providing welfare facilities to industrial workers and their families...',
      tags: ['workers welfare', 'welfare fund', 'employee benefits', 'social security'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3890,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 20)),
    ),
    LawDocument(
      id: 'labor_6',
      title: 'Workmen Compensation Act 1923',
      description: 'Law providing compensation for work-related injuries and accidents',
      category: 'Labor Law',
      publishedDate: DateTime(1923, 3, 8),
      documentType: 'Act',
      content: 'The Act provides for compensation to workmen for injuries arising out of and in the course of employment...',
      tags: ['workmen compensation', 'work injury', 'employee compensation', 'occupational hazards'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5670,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'labor_7',
      title: 'Shops and Establishments Ordinance 1969',
      description: 'Law regulating working conditions in shops and commercial establishments',
      category: 'Labor Law',
      publishedDate: DateTime(1969, 7, 20),
      documentType: 'Ordinance',
      content: 'The Ordinance regulates working hours, holidays, and conditions of service in shops and commercial establishments...',
      tags: ['shops regulation', 'establishment law', 'working hours', 'commercial employment'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4120,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 10)),
    ),
    LawDocument(
      id: 'labor_8',
      title: 'Social Security Ordinance 1965',
      description: 'Law providing social security benefits to workers',
      category: 'Labor Law',
      publishedDate: DateTime(1965, 1, 19),
      documentType: 'Ordinance',
      content: 'The Ordinance provides for social security benefits including medical care, cash benefits during sickness, and employment injury benefits...',
      tags: ['social security', 'medical benefits', 'sickness benefits', 'worker insurance'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6780,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'labor_9',
      title: 'Payment of Wages Act 1936',
      description: 'Law regulating payment of wages to workers',
      category: 'Labor Law',
      publishedDate: DateTime(1936, 4, 23),
      documentType: 'Act',
      content: 'The Act regulates payment of wages, prevents unauthorized deductions, and ensures timely payment to workers...',
      tags: ['wage payment', 'salary regulation', 'deduction control', 'timely payment'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5340,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 14)),
    ),
    LawDocument(
      id: 'labor_10',
      title: 'West Pakistan Maternity Benefit Ordinance 1958',
      description: 'Law providing maternity benefits to female workers',
      category: 'Labor Law',
      publishedDate: DateTime(1958, 12, 31),
      documentType: 'Ordinance',
      content: 'The Ordinance provides for maternity benefits, leave entitlements, and protection of employment for female workers...',
      tags: ['maternity benefits', 'female workers', 'maternity leave', 'employment protection'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3560,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 7)),
    ),
    
    // Property Law
    LawDocument(
      id: '12',
      title: 'Transfer of Property Act 1882',
      description: 'Law governing transfer of immovable property in Pakistan',
      category: 'Property Law',
      publishedDate: DateTime(1882, 7, 1),
      documentType: 'Act',
      content: 'The Transfer of Property Act 1882 governs the transfer of immovable property in Pakistan. It defines various modes of transfer including sale, mortgage, lease, exchange, and gift...',
      tags: ['property transfer', 'immovable property', 'sale', 'mortgage', 'lease'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 8760,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 15)),
    ),
    
    LawDocument(
      id: '13',
      title: 'Registration Act 1908',
      description: 'Law governing registration of documents and property transactions',
      category: 'Property Law',
      publishedDate: DateTime(1908, 1, 1),
      documentType: 'Act',
      content: 'The Registration Act 1908 provides for the registration of documents relating to immovable property. It ensures the authenticity and legal validity of property transactions...',
      tags: ['registration', 'documents', 'property transactions', 'authenticity'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 5680,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'prop_3',
      title: 'Land Revenue Act 1967',
      description: 'Law governing land revenue and land administration',
      category: 'Property Law',
      publishedDate: DateTime(1967, 2, 2),
      documentType: 'Act',
      content: 'The Land Revenue Act 1967 governs land revenue assessment, collection, and land administration in Pakistan...',
      tags: ['land revenue', 'land administration', 'revenue assessment', 'agricultural land'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4320,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    LawDocument(
      id: 'prop_4',
      title: 'Stamp Act 1899',
      description: 'Law governing stamp duty on documents and instruments',
      category: 'Property Law',
      publishedDate: DateTime(1899, 7, 1),
      documentType: 'Act',
      content: 'The Stamp Act 1899 prescribes stamp duty on various documents and instruments including property transactions...',
      tags: ['stamp duty', 'documents', 'instruments', 'property transactions'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 6780,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    LawDocument(
      id: 'prop_5',
      title: 'Partition Act 1893',
      description: 'Law governing partition of joint property',
      category: 'Property Law',
      publishedDate: DateTime(1893, 3, 9),
      documentType: 'Act',
      content: 'The Partition Act 1893 provides for the partition of joint property among co-owners and settlement of disputes...',
      tags: ['partition', 'joint property', 'co-ownership', 'property disputes'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 3450,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    LawDocument(
      id: 'prop_6',
      title: 'Easements Act 1882',
      description: 'Law governing easements and rights over property',
      category: 'Property Law',
      publishedDate: DateTime(1882, 12, 1),
      documentType: 'Act',
      content: 'The Easements Act 1882 defines and regulates easements, rights of way, and other rights over immovable property...',
      tags: ['easements', 'rights of way', 'property rights', 'servitudes'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 2890,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    LawDocument(
      id: 'prop_7',
      title: 'Specific Relief Act 1877',
      description: 'Law providing specific relief in property matters',
      category: 'Property Law',
      publishedDate: DateTime(1877, 3, 1),
      documentType: 'Act',
      content: 'The Specific Relief Act 1877 provides for specific performance of contracts, recovery of possession, and other specific reliefs in property matters...',
      tags: ['specific relief', 'specific performance', 'possession', 'property contracts'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 5120,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 16)),
    ),
    LawDocument(
      id: 'prop_8',
      title: 'Limitation Act 1908',
      description: 'Law prescribing limitation periods for property suits',
      category: 'Property Law',
      publishedDate: DateTime(1908, 1, 1),
      documentType: 'Act',
      content: 'The Limitation Act 1908 prescribes the limitation periods for filing suits related to property and other civil matters...',
      tags: ['limitation', 'time limits', 'property suits', 'civil procedure'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 7340,
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    LawDocument(
      id: 'prop_9',
      title: 'Colonization of Government Lands Act 1912',
      description: 'Law governing colonization and settlement of government lands',
      category: 'Property Law',
      publishedDate: DateTime(1912, 2, 15),
      documentType: 'Act',
      content: 'The Act governs the colonization and settlement of government lands, allocation to settlers, and land development...',
      tags: ['government lands', 'colonization', 'land settlement', 'land development'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 2670,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 20)),
    ),
    LawDocument(
      id: 'prop_10',
      title: 'Pre-emption Act 1913',
      description: 'Law governing pre-emption rights in property transactions',
      category: 'Property Law',
      publishedDate: DateTime(1913, 4, 10),
      documentType: 'Act',
      content: 'The Pre-emption Act 1913 governs the right of pre-emption in property sales, allowing certain persons to purchase property in preference to others...',
      tags: ['pre-emption', 'property sales', 'preferential rights', 'land transactions'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 4560,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    
    // Tax Law
    LawDocument(
      id: '14',
      title: 'Income Tax Ordinance 2001',
      description: 'Comprehensive law governing income tax in Pakistan',
      category: 'Tax Law',
      publishedDate: DateTime(2001, 9, 13),
      documentType: 'Ordinance',
      content: 'The Income Tax Ordinance 2001 is the primary legislation governing income tax in Pakistan. It defines taxable income, tax rates, exemptions, and procedures for assessment and collection...',
      tags: ['income tax', 'taxation', 'assessment', 'exemptions'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 9450,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    
    LawDocument(
      id: '15',
      title: 'Sales Tax Act 1990',
      description: 'Law governing sales tax and value-added tax in Pakistan',
      category: 'Tax Law',
      publishedDate: DateTime(1990, 7, 1),
      documentType: 'Act',
      content: 'The Sales Tax Act 1990 governs the levy and collection of sales tax in Pakistan. It covers the registration of taxpayers, tax rates, exemptions, and procedures for assessment...',
      tags: ['sales tax', 'VAT', 'registration', 'tax rates'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 7230,
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
    
    // Banking Law
    LawDocument(
      id: '16',
      title: 'Banking Companies Ordinance 1962',
      description: 'Law governing banking operations and financial institutions',
      category: 'Banking Law',
      publishedDate: DateTime(1962, 2, 9),
      documentType: 'Ordinance',
      content: 'The Banking Companies Ordinance 1962 regulates banking companies and financial institutions in Pakistan. It covers licensing, operations, supervision, and winding up of banks...',
      tags: ['banking', 'financial institutions', 'licensing', 'supervision'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4560,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 10)),
    ),
    
    // Environmental Law
    LawDocument(
      id: '17',
      title: 'Pakistan Environmental Protection Act 1997',
      description: 'Comprehensive environmental protection and pollution control law',
      category: 'Environmental Law',
      publishedDate: DateTime(1997, 12, 6),
      documentType: 'Act',
      content: 'The Pakistan Environmental Protection Act 1997 provides for the protection, conservation, rehabilitation and improvement of the environment, prevention and control of pollution...',
      tags: ['environmental protection', 'pollution control', 'conservation', 'rehabilitation'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 3840,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 20)),
    ),
    
    // Cyber Law
    LawDocument(
      id: '18',
      title: 'Prevention of Electronic Crimes Act 2016',
      description: 'Law addressing cybercrime and electronic offenses in Pakistan',
      category: 'Cyber Law',
      publishedDate: DateTime(2016, 8, 11),
      documentType: 'Act',
      content: 'The Prevention of Electronic Crimes Act 2016 addresses various cybercrimes including unauthorized access, data damage, electronic fraud, cyber terrorism, and online harassment...',
      tags: ['cybercrime', 'electronic crimes', 'data protection', 'cyber terrorism'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 6720,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    
    // Immigration Law
    LawDocument(
      id: '19',
      title: 'Foreigners Act 1946',
      description: 'Law governing entry, stay, and deportation of foreigners',
      category: 'Immigration Law',
      publishedDate: DateTime(1946, 12, 31),
      documentType: 'Act',
      content: 'The Foreigners Act 1946 governs the entry, stay, and deportation of foreigners in Pakistan. It provides powers to regulate the movement and activities of foreign nationals...',
      tags: ['foreigners', 'immigration', 'deportation', 'visa'],
      isBookmarked: true,
      fileUrl: null,
      filePath: null,
      viewCount: 2950,
      lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
    ),
    
    // Administrative Law
    LawDocument(
      id: '20',
      title: 'Civil Servants Act 1973',
      description: 'Law governing civil service and government employment',
      category: 'Administrative Law',
      publishedDate: DateTime(1973, 8, 28),
      documentType: 'Act',
      content: 'The Civil Servants Act 1973 governs the terms and conditions of service of civil servants in Pakistan. It covers recruitment, promotion, discipline, and retirement of government employees...',
      tags: ['civil service', 'government employment', 'recruitment', 'discipline'],
      isBookmarked: false,
      fileUrl: null,
      filePath: null,
      viewCount: 4120,
      lastUpdated: DateTime.now().subtract(const Duration(hours: 14)),
    ),
  ];

  static final List<LawCategory> mockCategories = [
    LawCategory(
      id: '1',
      name: 'Constitutional Law',
      description: 'Supreme law, fundamental rights, and constitutional provisions',
      iconName: 'account_balance',
      documentCount: 1,
      colorHex: '#1976D2',
    ),
    LawCategory(
      id: '2',
      name: 'Criminal Law',
      description: 'Criminal offenses, procedure, and penal provisions',
      iconName: 'gavel',
      documentCount: 2,
      colorHex: '#D32F2F',
    ),
    LawCategory(
      id: '3',
      name: 'Civil Law',
      description: 'Civil disputes, contracts, and civil procedure',
      iconName: 'balance',
      documentCount: 2,
      colorHex: '#1976D2',
    ),
    LawCategory(
      id: '4',
      name: 'Family Law',
      description: 'Marriage, divorce, guardianship, and family matters',
      iconName: 'family_restroom',
      documentCount: 2,
      colorHex: '#7B1FA2',
    ),
    LawCategory(
      id: '5',
      name: 'Corporate Law',
      description: 'Company incorporation, securities, and business regulations',
      iconName: 'business',
      documentCount: 2,
      colorHex: '#388E3C',
    ),
    LawCategory(
      id: '6',
      name: 'Labor Law',
      description: 'Industrial relations, workers rights, and employment',
      iconName: 'work',
      documentCount: 2,
      colorHex: '#455A64',
    ),
    LawCategory(
      id: '7',
      name: 'Property Law',
      description: 'Property transfer, registration, and real estate',
      iconName: 'home',
      documentCount: 2,
      colorHex: '#F57C00',
    ),
    LawCategory(
      id: '8',
      name: 'Tax Law',
      description: 'Income tax, sales tax, and taxation regulations',
      iconName: 'receipt_long',
      documentCount: 2,
      colorHex: '#C2185B',
    ),
    LawCategory(
      id: '9',
      name: 'Banking Law',
      description: 'Banking operations and financial institutions',
      iconName: 'account_balance_wallet',
      documentCount: 1,
      colorHex: '#00796B',
    ),
    LawCategory(
      id: '10',
      name: 'Environmental Law',
      description: 'Environmental protection and pollution control',
      iconName: 'eco',
      documentCount: 1,
      colorHex: '#689F38',
    ),
    LawCategory(
      id: '11',
      name: 'Cyber Law',
      description: 'Electronic crimes and cybersecurity regulations',
      iconName: 'security',
      documentCount: 1,
      colorHex: '#5E35B1',
    ),
    LawCategory(
      id: '12',
      name: 'Immigration Law',
      description: 'Foreign nationals, visa, and immigration matters',
      iconName: 'flight',
      documentCount: 1,
      colorHex: '#FF5722',
    ),
    LawCategory(
      id: '13',
      name: 'Administrative Law',
      description: 'Civil service and government administration',
      iconName: 'admin_panel_settings',
      documentCount: 1,
      colorHex: '#795548',
    ),
   ];
}
